{
 "title": "Citrea Sequencer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current L1 block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sequencer_current_l1_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sequencer_mempool_txs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Produce L2 block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sequencer_block_production_execution",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool inbound tx/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(sequencer_mempool_txs[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dry run transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sequencer_dry_run_execution", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Commit to L1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sequencer_send_commitment_execution",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commitment blocks count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sequencer_commitment_blocks_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}